### ISSUE TITLE
[Suggestion] Bookshelf keeps items when broken with silk touch

### ISSUE THREAD

**Issue by JustJP2K** [LOOHP/Bookshelf#1]
Being able to toggle an option in the config where when breaking the bookshelf with books inside it will stay. the Bookshelf becomes non stackable and shows the first 5 Books when hovered over and the rest in numbers, like a shulker. 
Would be a very nice feature :)

**Comment by LOOHP** [comment]
I might add that in the future, thanks for the suggestion!
