### ISSUE TITLE
CoreProtect doesn't log bookshelf interactions

### ISSUE THREAD

**Issue by Zoro-6191** [LOOHP/Bookshelf#10]
Hi, I'm not sure if you can even help it at all, but it would be cool if [CoreProtect](https://www.spigotmc.org/resources/coreprotect.8631) can log interactions so when admins do `/co inspect` it shows who recently interacted with that bookshelf.

**Comment by LOOHP** [comment]
I looked into this a while ago but found that there is no way to log custom container transactions. So until CoreProtect has this functionality, that doesn't seem possible.

**Comment by Zoro-6191** [comment]
but couldn't you detect if coreprotect is installed and use that particular db table and do it the manual way.. I mean it seems possible. But could be a bit of work so its fine if you decide not to.

**Comment by Zoro-6191** [comment]
[ss.jpg](https://user-images.githubusercontent.com/52291201/146393734-6027067e-d4f6-4b4e-86bd-6c38624c92c5.jpg)

yeah that looks alot of work for 1 thing haha

**Comment by LOOHP** [comment]
I mean if I do this I might as well implement my own logging/backup system XD
Maybe I will do something like that in the future, just maybe.

**Comment by Zoro-6191** [comment]
sounds good
