### ISSUE TITLE
Missing support for Plotsquared

### ISSUE THREAD

**Issue by ErythroCraft** [LOOHP/Bookshelf#4]
Hi.

After install PlotSquared v6 the server console say
[11:18:37] [Server thread/INFO]: [Bookshelf] This version of PlotSquared is not supported, only v4 and v5 is supported so far.
I hope you can update the plugin fast.

THX

**Comment by LOOHP** [comment]
Can you give this build a try?
https://drive.google.com/file/d/1F9xptw4KjIsDOgWXXMHXQflSyCNkvi5n/view?usp=sharing

**Comment by ErythroCraft** [comment]
Really good. Perfect. You can use it. 

Working with:

- Towny
- PlotSquared
- LWC [commands+perms]
- WorldGuard
- Essentials
- InteractionVisualizer

![Bild_2021-06-26_145918](https://user-images.githubusercontent.com/76217862/123513751-14a5a700-d68f-11eb-88ff-9ea67ad4fcb5.png)
