### ISSUE TITLE
[SUGGESTION] Add support for GriefDefender Claim Plugin

### ISSUE THREAD

**Issue by Tim-Rambo** [LOOHP/Bookshelf#6]
Spigot link:
https://www.spigotmc.org/resources/1-12-2-1-17-1-griefdefender-claim-plugin-grief-prevention-protection.68900/

**Comment by LOOHP** [comment]
Can you give this build a try to see if the hook works?
https://drive.google.com/file/d/1Omn3Zdor7xDsF--xN8oUfLH8xcGXgix7/view?usp=sharing

**Comment by LOOHP** [comment]
Closed Inactivity
